services:
  nginx:
    image: macbre/nginx-http3:latest
    ports:
      - "443:443/tcp"
      - "443:443/udp"
    volumes:
      - ./config/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./config/cert.pem:/etc/nginx/ssl/cert.pem:ro
      - ./config/key.pem:/etc/nginx/ssl/key.pem:ro
    networks:
      - private
    depends_on:
      - backend
      - swagger
    restart: unless-stopped
    user: "root"

  swagger:
    image: swaggerapi/swagger-ui
    volumes:
      - ./doc:/doc:ro
    networks: 
      - private
    environment:
      SWAGGER_JSON: /doc/openapi.yaml

  backend:
    build: 
      context: ./
      dockerfile: ./containers/php.dockerfile 
    volumes:
      - ./:/app:ro
    command: php /app/src/main.php
    networks:
      - private
    depends_on:
      - db
    restart: unless-stopped
    env_file:
      - .env
    deploy:
      mode: replicated
      replicas: 10

  db:
    image: mariadb:11.6.1-rc
    volumes:
      - ./db:/var/lib/mysql
    ports:
      - 3306:3306
    networks:
      - private
    restart: unless-stopped
    env_file:
      - .env

networks:
  private:

