openapi: 3.0.3
info:
  title: Guest Management API
  description: API for managing guests with CRUD operations.
  version: 1.0.0
servers:
  - url: http://localhost/api/v1
paths:
  /guest:
    post:
      summary: Create a new guest.
      operationId: createGuest
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guest'
      responses:
        '200':
          description: Guest created successfully.
          content:
            text/plain:
              schema:
                type: string
                example: "a3d9f93e-8b64-47e6-931b-c376c4d35d48"
        '403':
          description: Validation error.
    get:
      summary: List all guests.
      operationId: listGuests
      parameters:
        - name: offset
          in: query
          required: true
          schema:
            type: integer
            minimum: 0
            example: 0
        - name: limit
          in: query
          required: true
          schema:
            type: integer
            minimum: 1
            maximum: 100
            example: 10
      responses:
        '200':
          description: A list of guests.
          content:
            application/json:
              schema:
                type: object
                properties:
                  guests:
                    type: array
                    items:
                      $ref: '#/components/schemas/Guest'
        '403':
          description: Validation error.
  /guest/{uuid}:
    get:
      summary: Retrieve a guest by UUID.
      operationId: getGuest
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      responses:
        '200':
          description: Guest details.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Guest'
        '404':
          description: Guest not found.
    put:
      summary: Update a guest by UUID.
      operationId: updateGuest
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Guest'
      responses:
        '200':
          description: Guest updated successfully.
        '403':
          description: Validation error.
        '404':
          description: Guest not found.
    patch:
      summary: Partially update a guest by UUID.
      operationId: patchGuest
      parameters:
        - name: uuid
          in: path
          required: true
          schema:
            type: string
            format: uuid
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GuestOptionalFields'
      responses:
        '200':
          description: Guest updated successfully.
        '403':
          description: Validation error.
        '404':
          description: Guest not found.
components:
  schemas:
    Guest:
      type: object
      required:
        - name
        - surname
        - email
        - phone
      properties:
        uuid:
          type: string
          format: uuid
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        country:
          type: string
          description: ISO 3166-1 alpha-2 country code.
    GuestOptionalFields:
      type: object
      properties:
        name:
          type: string
        surname:
          type: string
        email:
          type: string
          format: email
        phone:
          type: string
        country:
          type: string
          description: ISO 3166-1 alpha-2 country code.
